In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
car_data = pd.read_csv("car_fuel_efficiency_2026.csv")

In [ ]:
car_data.tail()

In [ ]:
car_data.info()

In [ ]:
car_data.describe()

In [ ]:
car_data.index

In [ ]:
car_data.columns

In [ ]:
car_data["fuel_type"]

In [ ]:
car_data[
    (car_data["origin"] == "Asia") &
    (car_data["fuel_efficiency_mpg"] == car_data["fuel_efficiency_mpg"].max())
]

In [ ]:
car_data["horsepower"]

In [74]:
horsepower_median = car_data["horsepower"].median()
horsepower_median

np.float64(254.0)

In [75]:
horsepower_mode = car_data["horsepower"].mode()[0]
horsepower_mode

np.float64(252.0)

In [76]:
car_data["horsepower"] = car_data["horsepower"].fillna(horsepower_mode)

In [77]:
horsepower_median_filled = car_data["horsepower"].median()
horsepower_median_filled

np.float64(252.0)

In [78]:
import numpy as np

asia_cars = car_data[car_data["origin"] == "Asia"]
subset = asia_cars[["vehicle_weight", "model_year"]]
first_7 = subset.head(7)
X = first_7.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [79]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [80]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [81]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [82]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [83]:
w_sum = w.sum()
w_sum

np.float64(0.36919696904925486)